let number = 10;
let price = 20.5;
let city = "Hà nội";
document.write("<ul>");
document.write("<li><b>Biến number</b> kiểu số nguyên, có giá trị là <b>" + number + "</b></li>");
document.write("<li><b>Biến price</b> kiểu số thực, có giá trị là <b>" + price + "</b></li>");
document.write("<li><b>Biến status</b> kiểu logic, có giá trị là <b>" + status + "</b></li>");
document.write("<li><b>Biến city</b> kiểu chuỗi, có giá trị là <b>\"" + city + "\"</b></li>");
document.write("<li>Sử dụng hàm <b>document.write()</b> để viết kết quả ra màn hình.</li>");
document.write("</ul>");
